version: '3.7'
services:
  db:
    image: postgres:13.3-alpine
    restart: "no"
    networks:
      - installment-loc
    volumes:
      - ./loc/db:/var/lib/postgresql/data
      - $PWD/services/repository/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123