global:
  scrape_interval: 1m

rule_files:
  - "postgresql.yml"

scrape_configs:
  - job_name: 'postgres-exporter'
    metrics_path: '/metrics'
    honor_labels: true
    scrape_interval: 300s
    scrape_timeout: 60s
    static_configs:
      - targets: ['postgres-exporter-pgserver94:9187','postgres-exporter-pgserver92:9187']

  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

#remote_write:
#  - url: "<Your Prometheus remote_write endpoint>"
#    basic_auth:
#      username: "<Your Grafana Username>"
#      password: "<Your Grafana API key>"