// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: proto/repository.proto

package repository_proto

import (
	utils_proto "OverflowBackend/proto/utils_proto"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoByUsernameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GetUserInfoByUsernameRequest) Reset() {
	*x = GetUserInfoByUsernameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByUsernameRequest) ProtoMessage() {}

func (x *GetUserInfoByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserInfoByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetUserInfoByIdRequest) Reset() {
	*x = GetUserInfoByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByIdRequest) ProtoMessage() {}

func (x *GetUserInfoByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoByIdRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *utils_proto.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{2}
}

func (x *AddUserRequest) GetUser() *utils_proto.User {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangeForm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *utils_proto.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Data string            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ChangeForm) Reset() {
	*x = ChangeForm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeForm) ProtoMessage() {}

func (x *ChangeForm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeForm.ProtoReflect.Descriptor instead.
func (*ChangeForm) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeForm) GetUser() *utils_proto.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ChangeForm) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetIncomeMailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetIncomeMailsRequest) Reset() {
	*x = GetIncomeMailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncomeMailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncomeMailsRequest) ProtoMessage() {}

func (x *GetIncomeMailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncomeMailsRequest.ProtoReflect.Descriptor instead.
func (*GetIncomeMailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{4}
}

func (x *GetIncomeMailsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOutcomeMailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetOutcomeMailsRequest) Reset() {
	*x = GetOutcomeMailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOutcomeMailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutcomeMailsRequest) ProtoMessage() {}

func (x *GetOutcomeMailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutcomeMailsRequest.ProtoReflect.Descriptor instead.
func (*GetOutcomeMailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{5}
}

func (x *GetOutcomeMailsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail *utils_proto.Mail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
}

func (x *AddMailRequest) Reset() {
	*x = AddMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMailRequest) ProtoMessage() {}

func (x *AddMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMailRequest.ProtoReflect.Descriptor instead.
func (*AddMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{6}
}

func (x *AddMailRequest) GetMail() *utils_proto.Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type DeleteMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail     *utils_proto.Mail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	Username string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *DeleteMailRequest) Reset() {
	*x = DeleteMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMailRequest) ProtoMessage() {}

func (x *DeleteMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMailRequest.ProtoReflect.Descriptor instead.
func (*DeleteMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMailRequest) GetMail() *utils_proto.Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *DeleteMailRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ReadMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail *utils_proto.Mail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
}

func (x *ReadMailRequest) Reset() {
	*x = ReadMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMailRequest) ProtoMessage() {}

func (x *ReadMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMailRequest.ProtoReflect.Descriptor instead.
func (*ReadMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{8}
}

func (x *ReadMailRequest) GetMail() *utils_proto.Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type GetMailInfoByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId int32 `protobuf:"varint,1,opt,name=mailId,proto3" json:"mailId,omitempty"`
}

func (x *GetMailInfoByIdRequest) Reset() {
	*x = GetMailInfoByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMailInfoByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMailInfoByIdRequest) ProtoMessage() {}

func (x *GetMailInfoByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMailInfoByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMailInfoByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{9}
}

func (x *GetMailInfoByIdRequest) GetMailId() int32 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type ResponseUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *utils_proto.DatabaseResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	User     *utils_proto.User             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ResponseUser) Reset() {
	*x = ResponseUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUser) ProtoMessage() {}

func (x *ResponseUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUser.ProtoReflect.Descriptor instead.
func (*ResponseUser) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseUser) GetResponse() *utils_proto.DatabaseResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResponseUser) GetUser() *utils_proto.User {
	if x != nil {
		return x.User
	}
	return nil
}

type ResponseMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *utils_proto.DatabaseResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Mail     *utils_proto.Mail             `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail,omitempty"`
}

func (x *ResponseMail) Reset() {
	*x = ResponseMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMail) ProtoMessage() {}

func (x *ResponseMail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMail.ProtoReflect.Descriptor instead.
func (*ResponseMail) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{11}
}

func (x *ResponseMail) GetResponse() *utils_proto.DatabaseResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResponseMail) GetMail() *utils_proto.Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type ResponseMails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *utils_proto.DatabaseResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Mails    []*utils_proto.Mail           `protobuf:"bytes,2,rep,name=mails,proto3" json:"mails,omitempty"`
}

func (x *ResponseMails) Reset() {
	*x = ResponseMails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_repository_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMails) ProtoMessage() {}

func (x *ResponseMails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMails.ProtoReflect.Descriptor instead.
func (*ResponseMails) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{12}
}

func (x *ResponseMails) GetResponse() *utils_proto.DatabaseResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResponseMails) GetMails() []*utils_proto.Mail {
	if x != nil {
		return x.Mails
	}
	return nil
}

var File_proto_repository_proto protoreflect.FileDescriptor

var file_proto_repository_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x0e, 0x41,
	0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x74,
	0x69, 0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x41,
	0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x1f, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x4d, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x50, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x73, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x0f, 0x52, 0x65, 0x61,
	0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x73, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x30, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22,
	0x64, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x33, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x64, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x33, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73,
	0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x67, 0x0a, 0x0d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x33, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x6d,
	0x61, 0x69, 0x6c, 0x73, 0x32, 0x91, 0x08, 0x0a, 0x12, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x69, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x28, 0x2e, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x20, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a,
	0x12, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6f, 0x72,
	0x6d, 0x1a, 0x17, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x13,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6f, 0x72,
	0x6d, 0x1a, 0x17, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x12,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d,
	0x1a, 0x17, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x27, 0x2e,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x28, 0x2e, 0x72,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x4d, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x12,
	0x23, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x2e, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x28, 0x2e, 0x72,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_repository_proto_rawDescOnce sync.Once
	file_proto_repository_proto_rawDescData = file_proto_repository_proto_rawDesc
)

func file_proto_repository_proto_rawDescGZIP() []byte {
	file_proto_repository_proto_rawDescOnce.Do(func() {
		file_proto_repository_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_repository_proto_rawDescData)
	})
	return file_proto_repository_proto_rawDescData
}

var file_proto_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_repository_proto_goTypes = []interface{}{
	(*GetUserInfoByUsernameRequest)(nil), // 0: repository_proto.GetUserInfoByUsernameRequest
	(*GetUserInfoByIdRequest)(nil),       // 1: repository_proto.GetUserInfoByIdRequest
	(*AddUserRequest)(nil),               // 2: repository_proto.AddUserRequest
	(*ChangeForm)(nil),                   // 3: repository_proto.ChangeForm
	(*GetIncomeMailsRequest)(nil),        // 4: repository_proto.GetIncomeMailsRequest
	(*GetOutcomeMailsRequest)(nil),       // 5: repository_proto.GetOutcomeMailsRequest
	(*AddMailRequest)(nil),               // 6: repository_proto.AddMailRequest
	(*DeleteMailRequest)(nil),            // 7: repository_proto.DeleteMailRequest
	(*ReadMailRequest)(nil),              // 8: repository_proto.ReadMailRequest
	(*GetMailInfoByIdRequest)(nil),       // 9: repository_proto.GetMailInfoByIdRequest
	(*ResponseUser)(nil),                 // 10: repository_proto.ResponseUser
	(*ResponseMail)(nil),                 // 11: repository_proto.ResponseMail
	(*ResponseMails)(nil),                // 12: repository_proto.ResponseMails
	(*utils_proto.User)(nil),             // 13: utils.User
	(*utils_proto.Mail)(nil),             // 14: utils.Mail
	(*utils_proto.DatabaseResponse)(nil), // 15: utils.DatabaseResponse
}
var file_proto_repository_proto_depIdxs = []int32{
	13, // 0: repository_proto.AddUserRequest.user:type_name -> utils.User
	13, // 1: repository_proto.ChangeForm.user:type_name -> utils.User
	14, // 2: repository_proto.AddMailRequest.mail:type_name -> utils.Mail
	14, // 3: repository_proto.DeleteMailRequest.mail:type_name -> utils.Mail
	14, // 4: repository_proto.ReadMailRequest.mail:type_name -> utils.Mail
	15, // 5: repository_proto.ResponseUser.response:type_name -> utils.DatabaseResponse
	13, // 6: repository_proto.ResponseUser.user:type_name -> utils.User
	15, // 7: repository_proto.ResponseMail.response:type_name -> utils.DatabaseResponse
	14, // 8: repository_proto.ResponseMail.mail:type_name -> utils.Mail
	15, // 9: repository_proto.ResponseMails.response:type_name -> utils.DatabaseResponse
	14, // 10: repository_proto.ResponseMails.mails:type_name -> utils.Mail
	0,  // 11: repository_proto.DatabaseRepository.GetUserInfoByUsername:input_type -> repository_proto.GetUserInfoByUsernameRequest
	1,  // 12: repository_proto.DatabaseRepository.GetUserInfoById:input_type -> repository_proto.GetUserInfoByIdRequest
	2,  // 13: repository_proto.DatabaseRepository.AddUser:input_type -> repository_proto.AddUserRequest
	3,  // 14: repository_proto.DatabaseRepository.ChangeUserPassword:input_type -> repository_proto.ChangeForm
	3,  // 15: repository_proto.DatabaseRepository.ChangeUserFirstName:input_type -> repository_proto.ChangeForm
	3,  // 16: repository_proto.DatabaseRepository.ChangeUserLastName:input_type -> repository_proto.ChangeForm
	4,  // 17: repository_proto.DatabaseRepository.GetIncomeMails:input_type -> repository_proto.GetIncomeMailsRequest
	5,  // 18: repository_proto.DatabaseRepository.GetOutcomeMails:input_type -> repository_proto.GetOutcomeMailsRequest
	6,  // 19: repository_proto.DatabaseRepository.AddMail:input_type -> repository_proto.AddMailRequest
	7,  // 20: repository_proto.DatabaseRepository.DeleteMail:input_type -> repository_proto.DeleteMailRequest
	8,  // 21: repository_proto.DatabaseRepository.ReadMail:input_type -> repository_proto.ReadMailRequest
	9,  // 22: repository_proto.DatabaseRepository.GetMailInfoById:input_type -> repository_proto.GetMailInfoByIdRequest
	10, // 23: repository_proto.DatabaseRepository.GetUserInfoByUsername:output_type -> repository_proto.ResponseUser
	10, // 24: repository_proto.DatabaseRepository.GetUserInfoById:output_type -> repository_proto.ResponseUser
	15, // 25: repository_proto.DatabaseRepository.AddUser:output_type -> utils.DatabaseResponse
	15, // 26: repository_proto.DatabaseRepository.ChangeUserPassword:output_type -> utils.DatabaseResponse
	15, // 27: repository_proto.DatabaseRepository.ChangeUserFirstName:output_type -> utils.DatabaseResponse
	15, // 28: repository_proto.DatabaseRepository.ChangeUserLastName:output_type -> utils.DatabaseResponse
	12, // 29: repository_proto.DatabaseRepository.GetIncomeMails:output_type -> repository_proto.ResponseMails
	12, // 30: repository_proto.DatabaseRepository.GetOutcomeMails:output_type -> repository_proto.ResponseMails
	15, // 31: repository_proto.DatabaseRepository.AddMail:output_type -> utils.DatabaseResponse
	15, // 32: repository_proto.DatabaseRepository.DeleteMail:output_type -> utils.DatabaseResponse
	15, // 33: repository_proto.DatabaseRepository.ReadMail:output_type -> utils.DatabaseResponse
	11, // 34: repository_proto.DatabaseRepository.GetMailInfoById:output_type -> repository_proto.ResponseMail
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_repository_proto_init() }
func file_proto_repository_proto_init() {
	if File_proto_repository_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_repository_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByUsernameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeForm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIncomeMailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOutcomeMailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMailInfoByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_repository_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_repository_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_repository_proto_goTypes,
		DependencyIndexes: file_proto_repository_proto_depIdxs,
		MessageInfos:      file_proto_repository_proto_msgTypes,
	}.Build()
	File_proto_repository_proto = out.File
	file_proto_repository_proto_rawDesc = nil
	file_proto_repository_proto_goTypes = nil
	file_proto_repository_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DatabaseRepositoryClient is the client API for DatabaseRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatabaseRepositoryClient interface {
	GetUserInfoByUsername(ctx context.Context, in *GetUserInfoByUsernameRequest, opts ...grpc.CallOption) (*ResponseUser, error)
	GetUserInfoById(ctx context.Context, in *GetUserInfoByIdRequest, opts ...grpc.CallOption) (*ResponseUser, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error)
	ChangeUserPassword(ctx context.Context, in *ChangeForm, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error)
	ChangeUserFirstName(ctx context.Context, in *ChangeForm, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error)
	ChangeUserLastName(ctx context.Context, in *ChangeForm, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error)
	GetIncomeMails(ctx context.Context, in *GetIncomeMailsRequest, opts ...grpc.CallOption) (*ResponseMails, error)
	GetOutcomeMails(ctx context.Context, in *GetOutcomeMailsRequest, opts ...grpc.CallOption) (*ResponseMails, error)
	AddMail(ctx context.Context, in *AddMailRequest, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error)
	DeleteMail(ctx context.Context, in *DeleteMailRequest, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error)
	ReadMail(ctx context.Context, in *ReadMailRequest, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error)
	GetMailInfoById(ctx context.Context, in *GetMailInfoByIdRequest, opts ...grpc.CallOption) (*ResponseMail, error)
}

type databaseRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseRepositoryClient(cc grpc.ClientConnInterface) DatabaseRepositoryClient {
	return &databaseRepositoryClient{cc}
}

func (c *databaseRepositoryClient) GetUserInfoByUsername(ctx context.Context, in *GetUserInfoByUsernameRequest, opts ...grpc.CallOption) (*ResponseUser, error) {
	out := new(ResponseUser)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/GetUserInfoByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) GetUserInfoById(ctx context.Context, in *GetUserInfoByIdRequest, opts ...grpc.CallOption) (*ResponseUser, error) {
	out := new(ResponseUser)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/GetUserInfoById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error) {
	out := new(utils_proto.DatabaseResponse)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) ChangeUserPassword(ctx context.Context, in *ChangeForm, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error) {
	out := new(utils_proto.DatabaseResponse)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/ChangeUserPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) ChangeUserFirstName(ctx context.Context, in *ChangeForm, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error) {
	out := new(utils_proto.DatabaseResponse)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/ChangeUserFirstName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) ChangeUserLastName(ctx context.Context, in *ChangeForm, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error) {
	out := new(utils_proto.DatabaseResponse)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/ChangeUserLastName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) GetIncomeMails(ctx context.Context, in *GetIncomeMailsRequest, opts ...grpc.CallOption) (*ResponseMails, error) {
	out := new(ResponseMails)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/GetIncomeMails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) GetOutcomeMails(ctx context.Context, in *GetOutcomeMailsRequest, opts ...grpc.CallOption) (*ResponseMails, error) {
	out := new(ResponseMails)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/GetOutcomeMails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) AddMail(ctx context.Context, in *AddMailRequest, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error) {
	out := new(utils_proto.DatabaseResponse)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/AddMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) DeleteMail(ctx context.Context, in *DeleteMailRequest, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error) {
	out := new(utils_proto.DatabaseResponse)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/DeleteMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) ReadMail(ctx context.Context, in *ReadMailRequest, opts ...grpc.CallOption) (*utils_proto.DatabaseResponse, error) {
	out := new(utils_proto.DatabaseResponse)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/ReadMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRepositoryClient) GetMailInfoById(ctx context.Context, in *GetMailInfoByIdRequest, opts ...grpc.CallOption) (*ResponseMail, error) {
	out := new(ResponseMail)
	err := c.cc.Invoke(ctx, "/repository_proto.DatabaseRepository/GetMailInfoById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseRepositoryServer is the server API for DatabaseRepository service.
type DatabaseRepositoryServer interface {
	GetUserInfoByUsername(context.Context, *GetUserInfoByUsernameRequest) (*ResponseUser, error)
	GetUserInfoById(context.Context, *GetUserInfoByIdRequest) (*ResponseUser, error)
	AddUser(context.Context, *AddUserRequest) (*utils_proto.DatabaseResponse, error)
	ChangeUserPassword(context.Context, *ChangeForm) (*utils_proto.DatabaseResponse, error)
	ChangeUserFirstName(context.Context, *ChangeForm) (*utils_proto.DatabaseResponse, error)
	ChangeUserLastName(context.Context, *ChangeForm) (*utils_proto.DatabaseResponse, error)
	GetIncomeMails(context.Context, *GetIncomeMailsRequest) (*ResponseMails, error)
	GetOutcomeMails(context.Context, *GetOutcomeMailsRequest) (*ResponseMails, error)
	AddMail(context.Context, *AddMailRequest) (*utils_proto.DatabaseResponse, error)
	DeleteMail(context.Context, *DeleteMailRequest) (*utils_proto.DatabaseResponse, error)
	ReadMail(context.Context, *ReadMailRequest) (*utils_proto.DatabaseResponse, error)
	GetMailInfoById(context.Context, *GetMailInfoByIdRequest) (*ResponseMail, error)
}

// UnimplementedDatabaseRepositoryServer can be embedded to have forward compatible implementations.
type UnimplementedDatabaseRepositoryServer struct {
}

func (*UnimplementedDatabaseRepositoryServer) GetUserInfoByUsername(context.Context, *GetUserInfoByUsernameRequest) (*ResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfoByUsername not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) GetUserInfoById(context.Context, *GetUserInfoByIdRequest) (*ResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfoById not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) AddUser(context.Context, *AddUserRequest) (*utils_proto.DatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) ChangeUserPassword(context.Context, *ChangeForm) (*utils_proto.DatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeUserPassword not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) ChangeUserFirstName(context.Context, *ChangeForm) (*utils_proto.DatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeUserFirstName not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) ChangeUserLastName(context.Context, *ChangeForm) (*utils_proto.DatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeUserLastName not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) GetIncomeMails(context.Context, *GetIncomeMailsRequest) (*ResponseMails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncomeMails not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) GetOutcomeMails(context.Context, *GetOutcomeMailsRequest) (*ResponseMails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutcomeMails not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) AddMail(context.Context, *AddMailRequest) (*utils_proto.DatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMail not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) DeleteMail(context.Context, *DeleteMailRequest) (*utils_proto.DatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMail not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) ReadMail(context.Context, *ReadMailRequest) (*utils_proto.DatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadMail not implemented")
}
func (*UnimplementedDatabaseRepositoryServer) GetMailInfoById(context.Context, *GetMailInfoByIdRequest) (*ResponseMail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMailInfoById not implemented")
}

func RegisterDatabaseRepositoryServer(s *grpc.Server, srv DatabaseRepositoryServer) {
	s.RegisterService(&_DatabaseRepository_serviceDesc, srv)
}

func _DatabaseRepository_GetUserInfoByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).GetUserInfoByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/GetUserInfoByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).GetUserInfoByUsername(ctx, req.(*GetUserInfoByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_GetUserInfoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).GetUserInfoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/GetUserInfoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).GetUserInfoById(ctx, req.(*GetUserInfoByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_ChangeUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeForm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).ChangeUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/ChangeUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).ChangeUserPassword(ctx, req.(*ChangeForm))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_ChangeUserFirstName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeForm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).ChangeUserFirstName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/ChangeUserFirstName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).ChangeUserFirstName(ctx, req.(*ChangeForm))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_ChangeUserLastName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeForm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).ChangeUserLastName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/ChangeUserLastName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).ChangeUserLastName(ctx, req.(*ChangeForm))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_GetIncomeMails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncomeMailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).GetIncomeMails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/GetIncomeMails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).GetIncomeMails(ctx, req.(*GetIncomeMailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_GetOutcomeMails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOutcomeMailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).GetOutcomeMails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/GetOutcomeMails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).GetOutcomeMails(ctx, req.(*GetOutcomeMailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_AddMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).AddMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/AddMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).AddMail(ctx, req.(*AddMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_DeleteMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).DeleteMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/DeleteMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).DeleteMail(ctx, req.(*DeleteMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_ReadMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).ReadMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/ReadMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).ReadMail(ctx, req.(*ReadMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRepository_GetMailInfoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMailInfoByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRepositoryServer).GetMailInfoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository_proto.DatabaseRepository/GetMailInfoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRepositoryServer).GetMailInfoById(ctx, req.(*GetMailInfoByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatabaseRepository_serviceDesc = grpc.ServiceDesc{
	ServiceName: "repository_proto.DatabaseRepository",
	HandlerType: (*DatabaseRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfoByUsername",
			Handler:    _DatabaseRepository_GetUserInfoByUsername_Handler,
		},
		{
			MethodName: "GetUserInfoById",
			Handler:    _DatabaseRepository_GetUserInfoById_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _DatabaseRepository_AddUser_Handler,
		},
		{
			MethodName: "ChangeUserPassword",
			Handler:    _DatabaseRepository_ChangeUserPassword_Handler,
		},
		{
			MethodName: "ChangeUserFirstName",
			Handler:    _DatabaseRepository_ChangeUserFirstName_Handler,
		},
		{
			MethodName: "ChangeUserLastName",
			Handler:    _DatabaseRepository_ChangeUserLastName_Handler,
		},
		{
			MethodName: "GetIncomeMails",
			Handler:    _DatabaseRepository_GetIncomeMails_Handler,
		},
		{
			MethodName: "GetOutcomeMails",
			Handler:    _DatabaseRepository_GetOutcomeMails_Handler,
		},
		{
			MethodName: "AddMail",
			Handler:    _DatabaseRepository_AddMail_Handler,
		},
		{
			MethodName: "DeleteMail",
			Handler:    _DatabaseRepository_DeleteMail_Handler,
		},
		{
			MethodName: "ReadMail",
			Handler:    _DatabaseRepository_ReadMail_Handler,
		},
		{
			MethodName: "GetMailInfoById",
			Handler:    _DatabaseRepository_GetMailInfoById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/repository.proto",
}
