server:
  port: 8080
  timeout:
    server: 30s
    read: 15s
    write: 10s
    idle: 5s
    csrf_timeout: 10s
  static:
    dir: "static"
    handle: "/static/"
  keys:
    csrf_authkey: "7ad7b8be40fef684833eaf00770082cf"
    auth_key: "aPdSgVkYp3s6v9y$B&E)H+MbQeThWmZq"
    enc_key: "cRfUjXn2r5u8x/A?D*G-KaPdSgVkYp3s"
  services:
    auth:
      address: "localhost"
      port: 8081
    profile:
      address: "localhost"
      port: 8082
    mailbox:
      address: "localhost"
      port: 8083
    folder_manager:
      address: "localhost"
      port: 8084
    database:
      address: "localhost"
      port: 8085
  session_manager: "standard"
  
database:
  user: "postgres"
  password: "123"
  host: "localhost"
  port: 5432
  dbname: "potgres"
