server:
  port: 8080
  timeout:
    server: 30s
    read: 15s
    write: 10s
    idle: 5s
  static:
    dir: "static"
    handle: "/static/"
  keys:
    csrf_token: ""
    auth_key: "aPdSgVkYp3s6v9y$B&E)H+MbQeThWmZq"
    enc_key: "cRfUjXn2r5u8x/A?D*G-KaPdSgVkYp3s"
  
database:
  type: "mock"
  user: "postgres"
  password: "123"
  host: "localhost"
  port: 5432
  dbname: "postgres"
