// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Роман Медников",
            "url": "https://vk.com/l____l____l____l____l____l"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/folder/add": {
            "get": {
                "tags": [
                    "folder_manager"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folder_manager"
                ],
                "summary": "Добавить папку с письмами для пользователя",
                "parameters": [
                    {
                        "description": "Форма запроса",
                        "name": "AddFolderForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddFolderForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Folder"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/delete": {
            "get": {
                "tags": [
                    "folder_manager"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folder_manager"
                ],
                "summary": "Удалить папку с письмами",
                "parameters": [
                    {
                        "description": "Форма запроса",
                        "name": "DeleteFolderForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteFolderForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folder_manager"
                ],
                "summary": "Получить список папок пользователя или список писем в определенной папке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя папки с письмами",
                        "name": "folder_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Ограничение на количество писем\\папок в списке",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение в списке писем\\папок",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список писем в папке.",
                        "schema": {
                            "$ref": "#/definitions/models.MailAddList"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/mail/add": {
            "get": {
                "tags": [
                    "folder_manager"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folder_manager"
                ],
                "summary": "Добавить письмо в папку с письмами по его id",
                "parameters": [
                    {
                        "description": "Форма запроса",
                        "name": "AddMailToFolderByIdForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddMailToFolderByIdForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/mail/add_form": {
            "get": {
                "tags": [
                    "folder_manager"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folder_manager"
                ],
                "summary": "Добавить письмо в папку с письмами по форме",
                "parameters": [
                    {
                        "description": "Форма запроса",
                        "name": "AddMailToFolderByObjectForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddMailToFolderByObjectForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/mail/delete": {
            "get": {
                "tags": [
                    "folder_manager"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folder_manager"
                ],
                "summary": "Удалить письмо из папки",
                "parameters": [
                    {
                        "description": "Форма запроса",
                        "name": "DeleteFolderMailForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteFolderMailForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/mail/move": {
            "get": {
                "tags": [
                    "folder_manager"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folder_manager"
                ],
                "summary": "Переместить письмо из одной папки в другую",
                "parameters": [
                    {
                        "description": "Форма запроса",
                        "name": "MoveFolderMailForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MoveFolderMailForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/rename": {
            "get": {
                "tags": [
                    "folder_manager"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folder_manager"
                ],
                "summary": "Переименовать папку с письмами",
                "parameters": [
                    {
                        "description": "Форма запроса",
                        "name": "ChangeFolderForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChangeFolderForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "tags": [
                    "auth"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Завершение сессии пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное завершение сессии.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует, сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/delete": {
            "get": {
                "tags": [
                    "mailbox"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "Удалить письмо по его id",
                "parameters": [
                    {
                        "description": "Форма запроса",
                        "name": "DeleteMailForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteMailForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Письмо не принадлежит пользователю, ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/get": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "Получение сообщения по его id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID запрашиваемого письма.",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Объект письма.",
                        "schema": {
                            "$ref": "#/definitions/models.Mail"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/income": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "Получение входящих сообщений",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ограничение на количество писем",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение в списке писем",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список входящих писем",
                        "schema": {
                            "$ref": "#/definitions/models.MailAddList"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/outcome": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "Получение исходящих сообщений",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ограничение на количество писем",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение в списке писем",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список исходящих писем",
                        "schema": {
                            "$ref": "#/definitions/models.MailAddList"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/read": {
            "get": {
                "tags": [
                    "mailbox"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "Отметить число прочитанным/непрочитанным по его id. При отсутствии параметра isread запрос отмечает письмо с заданным id прочитанным.",
                "parameters": [
                    {
                        "description": "Форма запроса",
                        "name": "ReadMailForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReadMailForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Письмо не принадлежит пользователю, ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/send": {
            "get": {
                "tags": [
                    "mailbox"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "Выполняет отправку письма получателю",
                "parameters": [
                    {
                        "description": "Форма письма",
                        "name": "MailForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MailForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная отправка письма.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Получатель не существует, ошибка БД.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Получение данных пользователя",
                "responses": {
                    "200": {
                        "description": "Информация о пользователе",
                        "schema": {
                            "$ref": "#/definitions/models.ProfileInfo"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует, сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, пользователь не найден, неверные данные сессии.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/profile/avatar": {
            "get": {
                "description": "Получение ссылки на аватарку текущего пользователя или пользователя с конкретным логином (username).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Получение ссылки на аватарку пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя пользователя, соответствующее аватарке.",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ссылка на аватарку в формате /{static_dir}/{file}.{ext}.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, пользователь не найден или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/profile/avatar/set": {
            "get": {
                "tags": [
                    "profile"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Установка/смена аватарки пользователя",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файл аватарки.",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное установка аватарки.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка валидации формы, БД или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/profile/change_password": {
            "get": {
                "tags": [
                    "profile"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Изменение пароля пользователя",
                "parameters": [
                    {
                        "description": "Форма изменение пароля.",
                        "name": "SettingsForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChangePasswordForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное изменение пароля.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка валидации формы, БД или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/profile/set": {
            "get": {
                "tags": [
                    "profile"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Изменение настроек пользователя",
                "parameters": [
                    {
                        "description": "Форма настроек пользователя.",
                        "name": "SettingsForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProfileSettingsForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное изменение настроек.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка валидации формы, БД или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/signin": {
            "get": {
                "tags": [
                    "auth"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выполняет аутентификацию и выставляет сессионый cookie с названием OverflowMail",
                "parameters": [
                    {
                        "description": "Форма входа пользователя",
                        "name": "SignInForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignInForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная аутентификация пользователя.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Пользователь не существует, ошибка БД или валидации формы.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        },
        "/signup": {
            "get": {
                "tags": [
                    "auth"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Выполняет регистрацию пользователя, НЕ выставляет сессионый cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выполняет регистрацию пользователя",
                "parameters": [
                    {
                        "description": "Форма регистрации пользователя",
                        "name": "SignUpForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Вход уже выполнен, либо успешная регистрация пользователя.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка валидации формы, БД или пользователь уже существует.",
                        "schema": {
                            "$ref": "#/definitions/pkg.JsonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddFolderForm": {
            "type": "object",
            "properties": {
                "folder_name": {
                    "type": "string"
                }
            }
        },
        "models.AddMailToFolderByIdForm": {
            "type": "object",
            "properties": {
                "folder_name": {
                    "type": "string"
                },
                "mail_id": {
                    "type": "integer"
                },
                "move": {
                    "type": "boolean"
                }
            }
        },
        "models.AddMailToFolderByObjectForm": {
            "type": "object",
            "properties": {
                "folder_name": {
                    "type": "string"
                },
                "form": {
                    "$ref": "#/definitions/models.MailForm"
                }
            }
        },
        "models.ChangeFolderForm": {
            "type": "object",
            "properties": {
                "folder_name": {
                    "type": "string"
                },
                "new_folder_name": {
                    "type": "string"
                }
            }
        },
        "models.ChangePasswordForm": {
            "type": "object",
            "properties": {
                "password_new": {
                    "type": "string",
                    "maxLength": 45
                },
                "password_new_confirmation": {
                    "type": "string",
                    "maxLength": 45
                },
                "password_old": {
                    "type": "string",
                    "maxLength": 45
                }
            }
        },
        "models.DeleteFolderForm": {
            "type": "object",
            "properties": {
                "folder_name": {
                    "type": "string"
                }
            }
        },
        "models.DeleteFolderMailForm": {
            "type": "object",
            "properties": {
                "folder_name": {
                    "type": "string"
                },
                "mail_id": {
                    "type": "integer"
                }
            }
        },
        "models.DeleteMailForm": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.Folder": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.FolderList": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "folders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Folder"
                    }
                }
            }
        },
        "models.Mail": {
            "type": "object",
            "properties": {
                "addressee": {
                    "type": "string",
                    "maxLength": 45
                },
                "date": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "read": {
                    "type": "boolean"
                },
                "sender": {
                    "type": "string",
                    "maxLength": 45
                },
                "text": {
                    "type": "string"
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "models.MailAddList": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "mails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MailAdditional"
                    }
                }
            }
        },
        "models.MailAdditional": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "mail": {
                    "$ref": "#/definitions/models.Mail"
                }
            }
        },
        "models.MailForm": {
            "type": "object",
            "properties": {
                "addressee": {
                    "type": "string",
                    "maxLength": 45
                },
                "files": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "theme": {
                    "type": "string",
                    "maxLength": 45
                }
            }
        },
        "models.MoveFolderMailForm": {
            "type": "object",
            "properties": {
                "folder_name_dest": {
                    "type": "string"
                },
                "folder_name_src": {
                    "type": "string"
                },
                "mail_id": {
                    "type": "integer"
                }
            }
        },
        "models.ProfileInfo": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string",
                    "maxLength": 45
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 45
                },
                "username": {
                    "type": "string",
                    "maxLength": 45
                }
            }
        },
        "models.ProfileSettingsForm": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string",
                    "maxLength": 45
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 45
                }
            }
        },
        "models.ReadMailForm": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isread": {
                    "type": "boolean"
                }
            }
        },
        "models.SignInForm": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 45
                },
                "username": {
                    "type": "string",
                    "maxLength": 45
                }
            }
        },
        "models.SignUpForm": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string",
                    "maxLength": 45
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 45
                },
                "password": {
                    "type": "string",
                    "maxLength": 45
                },
                "password_confirmation": {
                    "type": "string",
                    "maxLength": 45
                },
                "username": {
                    "type": "string",
                    "maxLength": 45
                }
            }
        },
        "pkg.JsonResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OverMail API",
	Description:      "API почтового сервиса команды Overflow.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
