// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Роман Медников",
            "url": "https://vk.com/l____l____l____l____l____l"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/folder/add": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Добавить папку с письмами для пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя папки.",
                        "name": "folder_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/add_mail": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Добавить письмо в папку с письмами",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя папки.",
                        "name": "folder_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID добавляемого письма.",
                        "name": "mail_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/delete": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Удалить папку с письмами",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя папки.",
                        "name": "folder_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Получить список папок пользователя или список писем в определенной папке",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID папки с письмами",
                        "name": "folder_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/folder/rename": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Переименовать папку с письмами",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Исходное имя папки.",
                        "name": "folder_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Новое имя папки.",
                        "name": "new_folder_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Завершение сессии пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное завершение сессии.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует, сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/delete": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Удалить письмо по его id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID запрашиваемого письма.",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Письмо не принадлежит пользователю, ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/get": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Получение сообщения по его id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID запрашиваемого письма.",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Объект письма.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.Mail"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/income": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Получение входящих сообщений",
                "responses": {
                    "200": {
                        "description": "Список входящих писем",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/utils_proto.MailAdditional"
                            }
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/outcome": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Получение исходящих сообщений",
                "responses": {
                    "200": {
                        "description": "Список исходящих писем",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/utils_proto.MailAdditional"
                            }
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/read": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Прочитать письмо по его id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID запрашиваемого письма.",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Письмо не принадлежит пользователю, ошибка БД, неверные GET параметры.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/mail/send": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Выполняет отправку письма получателю",
                "parameters": [
                    {
                        "description": "Форма письма",
                        "name": "MailForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils_proto.MailForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная отправка письма.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Получатель не существует, ошибка БД.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Получение данных пользователя",
                "responses": {
                    "200": {
                        "description": "Информация о пользователе",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.User"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует, сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, пользователь не найден, неверные данные сессии.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/profile/avatar": {
            "get": {
                "description": "Получение ссылки на аватарку текущего пользователя или пользователя с конкретным логином (username).",
                "produces": [
                    "application/json"
                ],
                "summary": "Получение ссылки на аватарку пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя пользователя, соответствующее аватарке.",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ссылка на аватарку в формате /{static_dir}/{file}.{ext}.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка БД, пользователь не найден или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/profile/avatar/set": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Установка/смена аватарки пользователя",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файл аватарки.",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное установка аватарки.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка валидации формы, БД или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/profile/set": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Изменение настроек пользователя",
                "parameters": [
                    {
                        "description": "Форма настроек пользователя.",
                        "name": "SettingsForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils_proto.ProfileSettingsForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное изменение настроек.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка валидации формы, БД или сессия не валидна.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/signin": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Выполняет аутентификацию и выставляет сессионый cookie с названием OverflowMail",
                "parameters": [
                    {
                        "description": "Форма входа пользователя",
                        "name": "SignInForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_proto.SignInForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная аутентификация пользователя.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Пользователь не существует, ошибка БД или валидации формы.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        },
        "/signup": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        },
                        "headers": {
                            "X-CSRF-Token": {
                                "type": "string",
                                "description": "CSRF токен"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Выполняет регистрацию пользователя, НЕ выставляет сессионый cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Выполняет регистрацию пользователя",
                "parameters": [
                    {
                        "description": "Форма регистрации пользователя",
                        "name": "SignUpForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_proto.SignUpForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "CSRF токен",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Вход уже выполнен, либо успешная регистрация пользователя.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка валидации формы, БД или пользователь уже существует.",
                        "schema": {
                            "$ref": "#/definitions/utils_proto.JsonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth_proto.SignInForm": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth_proto.SignUpForm": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "password_confirmation": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "utils_proto.JsonResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "utils_proto.Mail": {
            "type": "object",
            "properties": {
                "addressee": {
                    "type": "string"
                },
                "client_id": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "read": {
                    "type": "boolean"
                },
                "sender": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "utils_proto.MailAdditional": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "mail": {
                    "$ref": "#/definitions/utils_proto.Mail"
                }
            }
        },
        "utils_proto.MailForm": {
            "type": "object",
            "properties": {
                "addressee": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "utils_proto.ProfileSettingsForm": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "utils_proto.User": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OverMail API",
	Description:      "API почтового сервиса команды Overflow.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
