basePath: /v2
info:
  contact:
    email: jellybe@yandex.ru
    name: Роман Медников
    url: https://vk.com/l____l____l____l____l____l
  description: API почтового сервиса команды Overflow.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: OverMail API
  version: "1.0"
paths:
  /income:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Получение входящих сообщений
  /outcome:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Получение исходящих сообщений
  /profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Получение данных профиля пользователя
  /signin:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Выполняет аутентификацию пользователя
  /signout:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Завершение сессии пользователя
  /signup:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Выполняет регистрацию пользователя
swagger: "2.0"
