basePath: /
definitions:
  models.Mail:
    description: Структура письма
    properties:
      addressee:
        type: string
      date:
        type: string
      files:
        type: string
      id:
        type: integer
      sender:
        type: string
      text:
        type: string
      theme:
        type: string
    type: object
  models.User:
    description: Структура пользователя
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: jellybe@yandex.ru
    name: Роман Медников
    url: https://vk.com/l____l____l____l____l____l
  description: API почтового сервиса команды Overflow.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: OverMail API
  version: "1.0"
paths:
  /income:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Список входящих писем
          schema:
            items:
              $ref: '#/definitions/models.Mail'
            type: array
        "401":
          description: Access denied
        "500":
          description: ""
      summary: Получение входящих сообщений
  /logout:
    get:
      responses:
        "200":
          description: OK
        "401":
          description: Access denied
        "500":
          description: ""
      summary: Завершение сессии пользователя
  /outcome:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Список исходящих писем
          schema:
            items:
              $ref: '#/definitions/models.Mail'
            type: array
        "401":
          description: Access denied
        "500":
          description: ""
      summary: Получение исходящих сообщений
  /profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Информация о пользователе
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Access denied
        "500":
          description: ""
      summary: Получение данных профиля пользователя
  /signin:
    post:
      responses:
        "200":
          description: OK
        "500":
          description: ""
      summary: Выполняет аутентификацию пользователя
  /signup:
    post:
      responses:
        "200":
          description: OK
        "500":
          description: ""
      summary: Выполняет регистрацию пользователя
swagger: "2.0"
