name: Deploy

on:
  push:
    branches: [ OV-66 ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify dependencies
        run: go mod verify

#      - name: Download library
#        run: sudo apt-get update; sudo apt-get install libwebp-dev;

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run tests
        run: go test -cover ./... -coverprofile=profile; go tool cover -func profile